# Generated by Django 5.2 on 2025-04-04 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('statut', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('statut', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('couverture', models.ImageField(upload_to='couvertures/')),
                ('auteur', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('langue', models.CharField(choices=[('FR', 'Français'), ('EN', 'English'), ('ES', 'Español'), ('DE', 'Deutsch')], max_length=2)),
                ('format', models.CharField(choices=[('Paperback', 'Paperback'), ('Hardcover', 'Hardcover'), ('Ebook', 'Ebook'), ('Audiobook', 'Audiobook')], max_length=20)),
                ('date_publication', models.DateField()),
                ('editeur', models.CharField(max_length=255)),
                ('nombre_pages', models.PositiveIntegerField()),
                ('nombre_chapitres', models.PositiveIntegerField()),
                ('nombre_topics', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('categorie_ids', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres', to='e_commerce.categorie')),
                ('tags_ids', models.ManyToManyField(blank=True, to='e_commerce.tag')),
            ],
        ),
    ]
