# Generated by Django 5.2 on 2025-04-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_livre_created_at_livre_last_updated_at_livre_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='nombre_chapitres',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='nombre_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='nombre_topics',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
