# Generated by Django 5.2 on 2025-04-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_alter_livre_nombre_chapitres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='editeur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
