# Generated by Django 5.2 on 2025-04-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0005_alter_livre_editeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='date_publication',
            field=models.DateField(blank=True, null=True),
        ),
    ]
